### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by KarenHdez24** [Devesh2707/Knee-Osteoarthritis#1]
I am running your code and I'm getting that error:

224                 " Signaling Trainer to stop."
    225             )
--> 226         elif self.monitor_op(current - self.min_delta, self.best_score.to(trainer.lightning_module.device)):
    227             should_stop = False
    228             reason = self._improvement_message(current)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Could you help me to fix it, please?

**Comment by Devesh2707** [comment]
Can you tell me in which file exactly this problem occurred?

**Comment by KarenHdez24** [comment]
The problem occurred when I’m running the first run(2), I have set my google colab to have GPU as hardware acceletator, in other case, I was getting an error.


***@***.***D77CD8.6970CFA0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Devesh2707** [comment]
I ran the code in colab only, there was no error from my side.
Have you changed anything in the code that might me causing the error ?
![Github_Issue](https://user-images.githubusercontent.com/45910501/126322714-2d962b61-0e49-4871-a554-83e82252aa79.PNG)

**Comment by KarenHdez24** [comment]
I have solved the issue. What I’ve done ant it has worked for me it is to change in the function run()
This part:

move_metrics_to_cpu = False
instead of having “True”

Thanks for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Devesh2707** [comment]
Good that it worked, but do keep in my mind that keeping that parameter False, might run your gpu out of memory 😅
