### ISSUE TITLE
Deploy method

### ISSUE THREAD

**Issue by tommyngx** [Devesh2707/Knee-Osteoarthritis#2]
Could you please share your steps and experience to deploy your webapp?
Streamlit I believe it is the frontend only! how about backend? which way has you applied for your project?
Many thanks!

**Comment by Devesh2707** [comment]
Streamlit has their own deployment server where you can deploy your web app.
Steps are simple too,
1. First register in Streamlit Sharing
2. After recieving the invitation, login to your streamlit account and then go to the sharing tab and click on New App button.
3. Then you'll be required to paste the link of your Github Repo in the Repository box, select the branch and then the file which contains the main code for the app.
4. And then click on the Deploy button.
5. The domain for the app can be copied from the address bar of your browser
The app will remain online on the server for 7 days if no traffic is experienced. if the app is closed down, just open the domain and your app will be restarted.

**Comment by tommyngx** [comment]
> Streamlit has their own deployment server where you can deploy your web app.
> Steps are simple too,
> 
> 1. First register in Streamlit Sharing
> 2. After recieving the invitation, login to your streamlit account and then go to the sharing tab and click on New App button.
> 3. Then you'll be required to paste the link of your Github Repo in the Repository box, select the branch and then the file which contains the main code for the app.
> 4. And then click on the Deploy button.
> 5. The domain for the app can be copied from the address bar of your browser
>    The app will remain online on the server for 7 days if no traffic is experienced. if the app is closed down, just open the domain and your app will be restarted.

Thank for your sharing!
